"""P1 of the fourth external audit pass (2026-08-01).

One single lock carried every extra, so the production image shipped
ruff, mypy and pytest; the Docker build upgraded pip outside any lock;
the debug toolbar was a runtime dependency; the base images floated on
a mutable tag. These tests pin the three hashed locks, their
consistency, the dev extra, the multi-stage digest-pinned image and
the CI lanes that install their own lock.
"""
import glob
import os
import re
import tomllib

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

LOCKS = (
    "requirements.lock",
    "requirements-test.lock",
    "requirements-quality.lock",
)

TOOLING = (
    "pytest",
    "pytest-cov",
    "webtest",
    "ruff",
    "bandit",
    "mypy",
    "pip-audit",
    "pyramid-debugtoolbar",
)


def _read(*parts):
    with open(os.path.join(ROOT, *parts), encoding="utf-8") as handle:
        return handle.read()


def _pins(name):
    return {
        match.group(1).lower(): match.group(2)
        for match in re.finditer(
            r"(?m)^([A-Za-z0-9_.-]+)==([^ \\\n]+)", _read(name)
        )
    }


def _header(name):
    lines = []
    for line in _read(name).splitlines():
        if not line.startswith("#"):
            break
        lines.append(line)
    return "\n".join(lines)


def test_the_three_locks_exist_with_hashes():
    """Every lock is pip-compile output in hash-checking mode; each
    lane's header records the extra it was compiled with."""
    for name in LOCKS:
        lock = _read(name)
        assert "autogenerated by pip-compile" in lock, name
        assert "--hash=sha256:" in lock, name
    assert "--extra" not in _header("requirements.lock")
    assert "--extra=testing" in _header("requirements-test.lock")
    assert "--extra=quality" in _header("requirements-quality.lock")


def test_the_runtime_lock_ships_no_tooling():
    """§4 of the audit: the production image installed the full lock —
    test and quality tools included. The runtime lock must carry none
    of them, nor the debug toolbar."""
    runtime = _pins("requirements.lock")
    for tool in TOOLING:
        assert tool not in runtime, tool


def test_the_split_locks_extend_the_runtime_lock_identically():
    """The three locks come from the same seed: every runtime pin must
    appear at the exact same version in the two wider locks, which add
    their own lane's tools on top."""
    runtime = _pins("requirements.lock")
    test = _pins("requirements-test.lock")
    quality = _pins("requirements-quality.lock")
    for name, version in runtime.items():
        assert test.get(name) == version, (name, version, test.get(name))
        assert quality.get(name) == version, (
            name,
            version,
            quality.get(name),
        )
    for tool in ("pytest", "pytest-cov", "webtest"):
        assert tool in test, tool
    for tool in ("ruff", "bandit", "mypy", "pip-audit"):
        assert tool in quality, tool


def test_the_debug_toolbar_is_a_dev_extra_not_a_runtime_dependency():
    """The toolbar is only ever included by development.ini; as a
    runtime dependency it shipped in every production image."""
    with open(os.path.join(ROOT, "pyproject.toml"), "rb") as handle:
        pyproject = tomllib.load(handle)
    runtime = " ".join(pyproject["project"]["dependencies"]).lower()
    assert "debugtoolbar" not in runtime
    dev = " ".join(
        pyproject["project"]["optional-dependencies"]["dev"]
    ).lower()
    assert "pyramid_debugtoolbar" in dev


def test_the_pyramid_image_is_multi_stage_on_a_pinned_base():
    """§4: builder owns the compilers, runtime ships neither compiler
    nor tooling; both stages share one digest-pinned base; the venv
    installs the runtime lock in hash-checking mode; nothing is
    upgraded outside the lock."""
    dockerfile = _read("docker", "DockerfilePyramid")
    froms = re.findall(r"(?m)^FROM\s+(\S+)(\s+AS\s+\w+)?", dockerfile)
    assert len(froms) == 2, froms
    digests = {image for image, _ in froms}
    assert len(digests) == 1, digests
    assert re.fullmatch(
        r"ubuntu:24\.04@sha256:[0-9a-f]{64}", digests.pop()
    )
    assert "AS builder" in dockerfile
    assert "--require-hashes" in dockerfile
    assert "requirements-test.lock" not in dockerfile
    assert "--upgrade pip" not in dockerfile
    runtime_stage = dockerfile.rsplit("FROM ", 1)[1]
    assert "build-essential" not in runtime_stage


def test_every_base_image_is_pinned_by_digest():
    """A mutable tag is a supply-chain risk on every image, not just
    the application's."""
    for path in glob.glob(os.path.join(ROOT, "docker", "Dockerfile*")):
        content = open(path, encoding="utf-8").read()
        for match in re.finditer(r"(?m)^FROM\s+(\S+)", content):
            image = match.group(1)
            assert re.search(r"@sha256:[0-9a-f]{64}$", image), (
                path,
                image,
            )


def test_the_ci_lanes_install_their_own_lock():
    """tests.yml runs on the test lock, quality.yml on the quality
    lock, and pip-audit sweeps all three."""
    tests_ci = _read(".github", "workflows", "tests.yml")
    assert "requirements-test.lock" in tests_ci
    assert "requirements-quality.lock" not in tests_ci
    quality_ci = _read(".github", "workflows", "quality.yml")
    assert "requirements-quality.lock" in quality_ci
    for name in LOCKS:
        assert f"-r {name}" in quality_ci, name


def test_only_the_test_entrypoint_installs_and_only_the_test_lock():
    """The optional in-container extras install must stay inside a
    hashed lock — never the unpinned `.[testing]` extra. Sixth audit
    pass (§11.4): the PRODUCTION entrypoint no longer installs anything
    at runtime at all; the test entrypoint reads the lock from the
    compose bind-mount."""
    prod = _read("docker", "start_pyramid.sh")
    assert "pip install" not in prod
    test = _read("docker", "start_test_pyramid.sh")
    assert "requirements-test.lock" in test
    assert '.[testing]' not in test
